[project]
name = "ai-learn-notebooks"
version = "0.1.0"
description = "Personal learning notebooks for AI concepts and projects."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.6",
    "pandas>=2.3.2",
    "scikit-learn>=1.7.2",
]
